public enum TokenType {
    KW_POKEMON, KW_INT, KW_STRING, KW_BOOLEAN, KW_FUNCTION, KW_VOID, KW_IF, KW_ELSEIF, KW_ELSE, KW_WHILE,
    KW_FOR, KW_BREAK, KW_CONTINUE, KW_RETURN, KW_PRINT, KW_SHOW, KW_SPELLDATABASE, KW_MOVE1,
    KW_MOVE2, KW_MOVE3, KW_MOVE4,
//    KW_HP, KW_ATTACK, KW_DEFENSE, KW_NAME, KW_TYPE,
    KW_TRUE, KW_FALSE, IDENTIFIER, INT_LITERAL, STRING_LITERAL,
    OP_ASSIGN, OP_EQUALS, OP_PLUS_ASSIGN, OP_MINUS_ASSIGN, OP_PLUS, OP_MINUS, OP_MULTIPLY,
    OP_DIVIDE, OP_AND, OP_OR, OP_INCREMENT, OP_NOT, OP_NOTEQUAL, LPAREN, RPAREN, LBRACE, RBRACE, SEMICOLON, COMMA, DOT,
    OP_GREATER_OR_EQUAL, OP_GREATER, OP_LESS_OR_EQUAL, OP_LESS, LBRACKET, RBRACKET, KEYWORD_EOF
}
